name: NMSLauncher CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows-build:
    name: windows build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
        
    - name: Build with Gradle
      run: gradlew packageReleaseMsi

    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        path: build/compose
