name: NMSLauncher CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} build"
    
    steps:
    - uses: actions/checkout@v3
    
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Build with Gradle(Windows)
      if: matrix.platform == 'windows-latest'
      run: ./gradlew.bat packageDistributionForCurrentOS
    - name: Build with Gradle(macOS and Linux)
      if: matrix.platform != 'windows-latest'
      run: ./gradlew packageDistributionForCurrentOS

    - name: Upload artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: "${{ matrix.os }} artifact"
        path: build/compose/binaries
